package com.hasterapi.auth.infra.jpa

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Column
import org.springframework.data.relational.core.mapping.Table
import java.time.LocalDateTime

@Table("auth_history")
data class AuthHistoryEntity(
    @Id
    val pk: Long? = null,

    @Column("auth_id")
    val authId: String, //jwt id 저장

    val issuer: String,

    @Column("issue_date")
    val issueDate: LocalDateTime = LocalDateTime.now()
)

/*
CREATE TABLE auth_history
(
    pk         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id    VARCHAR(4100) NOT NULL,
    issuer     VARCHAR(100)  NOT NULL,
    issue_date TIMESTAMP     NOT NULL DEFAULT now()
);
 */