-- 1. 유저 마스터 (랭킹 필터링을 위한 성별, 지역, 생년월일 포함)
CREATE TABLE user_master (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             email       VARCHAR(255) UNIQUE NOT NULL,
                             name        VARCHAR(100) NOT NULL,
                             gender      VARCHAR(10),        -- 남, 여, 미상
                             birth_date  DATE,               -- 연령대 계산용
                             region      VARCHAR(50),        -- 서울, 부산 등
                             created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 2. 도서 SKU 마스터
CREATE TABLE book_sku_master (
                                 id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 isbn             VARCHAR(20) UNIQUE NOT NULL,
                                 title            VARCHAR(500) NOT NULL,
                                 author           VARCHAR(255) NOT NULL,
                                 publisher        VARCHAR(255),
                                 publish_year     INT,
                                 call_number      VARCHAR(100),
                                 category         VARCHAR(100),
                                 description      TEXT,
                                 cover_image_url  VARCHAR(1000),
                                 total_copies     INT NOT NULL DEFAULT 0,
                                 available_copies INT NOT NULL DEFAULT 0, -- 성능을 위한 역정규화 컬럼
                                 created_at       TIMESTAMP NOT NULL DEFAULT NOW(),
                                 updated_at       TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 3. 도서 개별 인벤토리 (실제 책 한 권 한 권)
CREATE TABLE book_inventory_detail (
                                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       book_sku_id  BIGINT REFERENCES book_sku_master(id),
                                       status       VARCHAR(50) NOT NULL DEFAULT 'AVAILABLE', -- AVAILABLE, LOANED, LOST, MAINTENANCE
                                       created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 4. 대출 마스터 (한 번의 대출 행위)
CREATE TABLE loan_master (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id     BIGINT REFERENCES user_master(id),
                             loan_date   TIMESTAMP NOT NULL DEFAULT NOW(),
                             due_date    TIMESTAMP NOT NULL,
                             total_items INT NOT NULL DEFAULT 1,
                             created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 5. 대출 상세 (개별 도서의 대출/반납 상태)
CREATE TABLE loan_detail (
                             id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             loan_master_id BIGINT REFERENCES loan_master(id),
                             book_sku_id    BIGINT REFERENCES book_sku_master(id),
                             inventory_id   BIGINT REFERENCES book_inventory_detail(id),
                             return_date    TIMESTAMP,
                             status         VARCHAR(50) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, RETURNED, OVERDUE
                             created_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 6. 예약 관리
CREATE TABLE reservation (
                             id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id          BIGINT REFERENCES user_master(id),
                             book_sku_id      BIGINT REFERENCES book_sku_master(id),
                             reservation_date TIMESTAMP NOT NULL DEFAULT NOW(),
                             available_date   TIMESTAMP,
                             expiry_date      TIMESTAMP,
                             status           VARCHAR(50) NOT NULL DEFAULT 'WAITING', -- WAITING, AVAILABLE, CANCELLED, COMPLETED
                             created_at       TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 7. 연체 및 과태료 관리
CREATE TABLE loan_overdue (
                              id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              loan_detail_id BIGINT REFERENCES loan_detail(id),
                              overdue_days   INT NOT NULL DEFAULT 0,
                              fine_amount    INT NOT NULL DEFAULT 0,
                              created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
                              updated_at     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 8. 도서 평점 및 리뷰
CREATE TABLE book_rating (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             book_sku_id BIGINT REFERENCES book_sku_master(id),
                             user_id     BIGINT REFERENCES user_master(id),
                             rating      INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
                             review      TEXT,
                             created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
                             updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
                             UNIQUE(book_sku_id, user_id) -- 중복 평점 방지
);