-- 인증/RBAC 스키마. (IDP 독립 계정 원장 + IDP 신원 링크 + 리프레시 토큰 회전/재사용탐지)
-- V1 과 동일 컨벤션: public 스키마, IDENTITY PK, TIMESTAMP.

-- 사내 계정 원장 (IDP 독립, 영속 기준점). 기준 식별자 = ldap_id
CREATE TABLE account
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ldap_id       VARCHAR(255) UNIQUE NOT NULL,
    email         VARCHAR(255),
    display_name  VARCHAR(255),
    department    VARCHAR(255),
    roles         VARCHAR(512) NOT NULL DEFAULT 'USER',   -- CSV: USER,SUPER_ADMIN ...
    status        VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | DISABLED
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMP
);

-- 외부 IDP 신원 ↔ Account 연결 (IDP 교체/다중 IDP 흡수)
CREATE TABLE identity_link
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT       NOT NULL REFERENCES account (id),
    provider   VARCHAR(32)  NOT NULL,  -- SSO | LDAP | GOOGLE | MOCK
    subject    VARCHAR(255) NOT NULL,  -- 해당 IDP 의 고유 식별자(sub/account_id)
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_identity_link UNIQUE (provider, subject)
);

-- 리프레시 토큰 (불투명 값의 SHA-256 해시만 저장). 회전 + 재사용 탐지(family).
CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT       NOT NULL REFERENCES account (id),
    token_hash VARCHAR(64)  NOT NULL UNIQUE,  -- SHA-256 hex
    family_id  VARCHAR(64)  NOT NULL,         -- 회전 체인 식별 (재사용 탐지 시 family 전체 폐기)
    expires_at TIMESTAMP    NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_refresh_token_account ON refresh_token (account_id);
CREATE INDEX idx_refresh_token_family ON refresh_token (family_id);

-- access token 발급 감사 로그 (jti 기록). 기존 AuthHistoryRecord 매핑 대상.
CREATE TABLE auth_history
(
    pk         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id    VARCHAR(4100) NOT NULL,  -- jwt id(jti)
    issuer     VARCHAR(100)  NOT NULL,
    issue_date TIMESTAMP     NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_auth_history_auth_id ON auth_history (auth_id);
