import type { JiraIssueDetail, JiraComponent, JiraReleaseVersion } from './jiraTypes';

export const MOCK_ISSUES: JiraIssueDetail[] = [
  {
    issueId: '1',
    issueKey: 'KAFKA-20066',
    issueType: 'TASK',
    summary: 'Implement KIP-1251: Assignment epochs for consumer groups',
    status: 'OPEN',
    priority: 'BLOCKER',
    resolution: 'Unresolved',
    assignee: 'Lucy Liu',
    reporter: 'Lucas Brutschy',
    creator: 'Lucas Brutschy',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2026-01-13T12:27:00',
    updatedAt: '2026-01-13T13:00:00',
    resolvedAt: null,
    components: 'clients',
    labels: 'kip-848',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'This is the implementation ticket to implement https://cwiki.apache.org/confluence/display/KAFKA/KIP-1251%3A+Assignment+epochs+for+consumer+groups once accepted.',
    createdDt: '2026-01-13T12:27:00',
    updatedDt: '2026-01-13T13:00:00',
    releaseVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    affectsVersions: [],
    votes: 0,
    watchers: 5,
    issueLinks: [
      {
        type: 'fixes',
        issueKey: 'KAFKA-19235',
        summary: 'STALE_MEMBER_EPOCH is mostly non-recoverable and forces lost commits when leaving ...',
        priority: 'BLOCKER',
        status: 'RESOLVED',
      },
      {
        type: 'links to',
        issueKey: 'GitHub Pull Request #21508',
        summary: 'GitHub Pull Request #21508',
        priority: 'MAJOR',
        status: 'OPEN',
        url: '#',
      },
      {
        type: 'links to',
        issueKey: 'GitHub Pull Request #21557',
        summary: 'GitHub Pull Request #21557',
        priority: 'MAJOR',
        status: 'OPEN',
        url: '#',
      },
      {
        type: 'links to',
        issueKey: 'GitHub Pull Request #21558',
        summary: 'GitHub Pull Request #21558',
        priority: 'MAJOR',
        status: 'OPEN',
        url: '#',
      },
    ],
    comments: [
      {
        id: 'c1',
        author: 'Matthias J. Sax',
        authorAvatar: null,
        date: '2026-02-13T21:35:00',
        content: 'Changed priority to blocker for this ticket, as I think we need to complete for for 4.3 release if we also want to do KIP-1274 with AK 4.3.',
      },
      {
        id: 'c2',
        author: 'Lucas Brutschy',
        authorAvatar: null,
        date: '2026-02-14T10:22:00',
        content: 'Agreed, this is a critical dependency for KIP-1274. I\'ll prioritize the implementation this sprint.',
      },
    ],
  },
  {
    issueId: '2',
    issueKey: 'KAFKA-20254',
    issueType: 'BUG',
    summary: 'Streams group replay fails after log compaction',
    status: 'OPEN',
    priority: 'CRITICAL',
    resolution: 'Unresolved',
    assignee: 'Sophie Turner',
    reporter: 'Jan Filipowski',
    creator: 'Jan Filipowski',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2026-01-20T09:15:00',
    updatedAt: '2026-01-21T14:30:00',
    resolvedAt: null,
    components: 'streams',
    labels: 'streams,bug',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'When a Kafka Streams application tries to replay a topic after log compaction has run, the group replay fails with an unexpected offset error.',
    createdDt: '2026-01-20T09:15:00',
    updatedDt: '2026-01-21T14:30:00',
    releaseVersions: [{ id: 'rv2', name: '4.2.1', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv2', name: '4.2.1', status: 'Unreleased' }],
    affectsVersions: [{ id: 'rv3', name: '4.2.0', status: 'Released' }],
    votes: 3,
    watchers: 8,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '3',
    issueKey: 'KAFKA-20185',
    issueType: 'TASK',
    summary: 'Verify existing IQv2 methods for MetadataTopics in Streams',
    status: 'OPEN',
    priority: 'MAJOR',
    resolution: 'Unresolved',
    assignee: 'Neha Narkhede',
    reporter: 'Bruno Cadonna',
    creator: 'Bruno Cadonna',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2026-01-15T11:00:00',
    updatedAt: '2026-01-18T16:45:00',
    resolvedAt: null,
    components: 'streams',
    labels: 'iqv2',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'We need to verify all existing IQv2 methods work correctly for MetadataTopics in the Streams framework.',
    createdDt: '2026-01-15T11:00:00',
    updatedDt: '2026-01-18T16:45:00',
    releaseVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    affectsVersions: [],
    votes: 1,
    watchers: 3,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '4',
    issueKey: 'KAFKA-20202',
    issueType: 'TASK',
    summary: 'Verify existing IQv2 methods for MetadataTopics with versioned stores',
    status: 'IN_PROGRESS',
    priority: 'MAJOR',
    resolution: 'Unresolved',
    assignee: 'Jun Rao',
    reporter: 'Bruno Cadonna',
    creator: 'Bruno Cadonna',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2026-01-16T10:00:00',
    updatedAt: '2026-01-19T12:00:00',
    resolvedAt: null,
    components: 'streams',
    labels: 'iqv2',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'Follow-up ticket to KAFKA-20185 for verifying IQv2 methods with versioned stores.',
    createdDt: '2026-01-16T10:00:00',
    updatedDt: '2026-01-19T12:00:00',
    releaseVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    affectsVersions: [],
    votes: 0,
    watchers: 2,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '5',
    issueKey: 'KAFKA-20106',
    issueType: 'IMPROVEMENT',
    summary: 'Improve behaviour of consumer assignment when partition count changes',
    status: 'OPEN',
    priority: 'MAJOR',
    resolution: 'Unresolved',
    assignee: 'Lucy Liu',
    reporter: 'David Jacot',
    creator: 'David Jacot',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2026-01-10T08:30:00',
    updatedAt: '2026-01-12T17:00:00',
    resolvedAt: null,
    components: 'consumer',
    labels: 'consumer,assignment',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'The current consumer assignment algorithm does not handle partition count changes gracefully. This improvement would make the behavior more predictable.',
    createdDt: '2026-01-10T08:30:00',
    updatedDt: '2026-01-12T17:00:00',
    releaseVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    affectsVersions: [],
    votes: 5,
    watchers: 12,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '6',
    issueKey: 'KAFKA-17337',
    issueType: 'IMPROVEMENT',
    summary: 'ConsumerConfig should default to Cooperative Sticky Assignor',
    status: 'OPEN',
    priority: 'MINOR',
    resolution: 'Unresolved',
    assignee: null,
    reporter: 'Guozhang Wang',
    creator: 'Guozhang Wang',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-08-05T14:00:00',
    updatedAt: '2025-12-01T09:00:00',
    resolvedAt: null,
    components: 'consumer',
    labels: 'config',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'The default partition assignment strategy should be updated to use the Cooperative Sticky Assignor for better rebalance performance.',
    createdDt: '2025-08-05T14:00:00',
    updatedDt: '2025-12-01T09:00:00',
    releaseVersions: [],
    fixVersions: [],
    affectsVersions: [],
    votes: 2,
    watchers: 4,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '7',
    issueKey: 'KAFKA-17281',
    issueType: 'TASK',
    summary: 'Remove old PAPI methods',
    status: 'IN_PROGRESS',
    priority: 'MINOR',
    resolution: 'Unresolved',
    assignee: 'Ismael Juma',
    reporter: 'Ismael Juma',
    creator: 'Ismael Juma',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-07-20T11:30:00',
    updatedAt: '2025-11-15T16:00:00',
    resolvedAt: null,
    components: 'admin',
    labels: 'cleanup,deprecation',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'Remove deprecated Producer API (PAPI) methods that have been marked for removal.',
    createdDt: '2025-07-20T11:30:00',
    updatedDt: '2025-11-15T16:00:00',
    releaseVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    affectsVersions: [],
    votes: 0,
    watchers: 1,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '8',
    issueKey: 'KAFKA-15529',
    issueType: 'BUG',
    summary: 'Flaky test ReassignReplicaShrinkTest.testShrinkingReplicas',
    status: 'OPEN',
    priority: 'MINOR',
    resolution: 'Unresolved',
    assignee: null,
    reporter: 'Colin McCabe',
    creator: 'Colin McCabe',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-04-01T09:00:00',
    updatedAt: '2025-09-10T14:00:00',
    resolvedAt: null,
    components: 'core',
    labels: 'flaky-test',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'The test ReassignReplicaShrinkTest.testShrinkingReplicas is flaky and fails intermittently in CI.',
    createdDt: '2025-04-01T09:00:00',
    updatedDt: '2025-09-10T14:00:00',
    releaseVersions: [],
    fixVersions: [],
    affectsVersions: [],
    votes: 0,
    watchers: 3,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '9',
    issueKey: 'KAFKA-19558',
    issueType: 'BUG',
    summary: 'kafka-consumer-groups.sh --describe shows wrong offset for empty groups',
    status: 'OPEN',
    priority: 'BLOCKER',
    resolution: 'Unresolved',
    assignee: 'Kirk True',
    reporter: 'Kirk True',
    creator: 'Kirk True',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-12-01T10:00:00',
    updatedAt: '2025-12-05T15:00:00',
    resolvedAt: null,
    components: 'tools',
    labels: 'consumer-group,tools',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'When using kafka-consumer-groups.sh --describe on an empty consumer group, the displayed offset is incorrect.',
    createdDt: '2025-12-01T10:00:00',
    updatedDt: '2025-12-05T15:00:00',
    releaseVersions: [{ id: 'rv2', name: '4.2.1', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv2', name: '4.2.1', status: 'Unreleased' }],
    affectsVersions: [{ id: 'rv3', name: '4.2.0', status: 'Released' }],
    votes: 7,
    watchers: 15,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '10',
    issueKey: 'KAFKA-16996',
    issueType: 'BUG',
    summary: 'The leastLoadedNode() function in kafka-clients returns wrong node after network failure',
    status: 'OPEN',
    priority: 'BLOCKER',
    resolution: 'Unresolved',
    assignee: null,
    reporter: 'Chia-Ping Tsai',
    creator: 'Chia-Ping Tsai',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-06-15T13:00:00',
    updatedAt: '2025-10-20T11:00:00',
    resolvedAt: null,
    components: 'clients',
    labels: 'network,leastLoadedNode',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'After a network failure, the leastLoadedNode() function returns a node that is already disconnected.',
    createdDt: '2025-06-15T13:00:00',
    updatedDt: '2025-10-20T11:00:00',
    releaseVersions: [],
    fixVersions: [],
    affectsVersions: [],
    votes: 4,
    watchers: 9,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '11',
    issueKey: 'KAFKA-10840',
    issueType: 'IMPROVEMENT',
    summary: 'Need way to catch auth issues in poll() loop without stopping processing',
    status: 'OPEN',
    priority: 'MAJOR',
    resolution: 'Unresolved',
    assignee: null,
    reporter: 'Ron Dagdag',
    creator: 'Ron Dagdag',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2023-11-01T08:00:00',
    updatedAt: '2025-08-15T10:00:00',
    resolvedAt: null,
    components: 'consumer',
    labels: 'auth,consumer',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'Currently, authentication failures in the poll() loop cause the consumer to stop processing. We need a way to handle auth issues gracefully.',
    createdDt: '2023-11-01T08:00:00',
    updatedDt: '2025-08-15T10:00:00',
    releaseVersions: [],
    fixVersions: [],
    affectsVersions: [],
    votes: 12,
    watchers: 25,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '12',
    issueKey: 'KAFKA-17146',
    issueType: 'BUG',
    summary: 'ZK to KRAFT migration stuck in pre-migration state',
    status: 'OPEN',
    priority: 'BLOCKER',
    resolution: 'Unresolved',
    assignee: 'Colin McCabe',
    reporter: 'Colin McCabe',
    creator: 'Colin McCabe',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-07-10T15:00:00',
    updatedAt: '2025-11-25T09:00:00',
    resolvedAt: null,
    components: 'kraft',
    labels: 'migration,zk-to-kraft',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'During ZK to KRAFT migration, the cluster gets stuck in pre-migration state and cannot proceed.',
    createdDt: '2025-07-10T15:00:00',
    updatedDt: '2025-11-25T09:00:00',
    releaseVersions: [{ id: 'rv2', name: '4.2.1', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv2', name: '4.2.1', status: 'Unreleased' }],
    affectsVersions: [{ id: 'rv3', name: '4.2.0', status: 'Released' }],
    votes: 8,
    watchers: 18,
    issueLinks: [],
    comments: [],
  },
  {
    issueId: '13',
    issueKey: 'KAFKA-19508',
    issueType: 'TASK',
    summary: 'Add missing metrics for consumer group coordinator',
    status: 'OPEN',
    priority: 'MINOR',
    resolution: 'Unresolved',
    assignee: 'David Jacot',
    reporter: 'David Jacot',
    creator: 'David Jacot',
    projectKey: 'KAFKA',
    projectName: 'Kafka',
    createdAt: '2025-11-20T10:30:00',
    updatedAt: '2025-12-10T14:00:00',
    resolvedAt: null,
    components: 'group-coordinator',
    labels: 'metrics',
    customProjectType: null,
    dateOfFirstResponse: null,
    startDate: null,
    endDate: null,
    description: 'Several metrics are missing from the consumer group coordinator that would help diagnose performance issues.',
    createdDt: '2025-11-20T10:30:00',
    updatedDt: '2025-12-10T14:00:00',
    releaseVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    fixVersions: [{ id: 'rv1', name: '4.3.0', status: 'Unreleased' }],
    affectsVersions: [],
    votes: 2,
    watchers: 4,
    issueLinks: [],
    comments: [],
  },
];

export const MOCK_COMPONENTS: JiraComponent[] = [
  { id: 'c1', name: 'admin', status: 'ACTIVE', issueCount: 296, lead: 'Neha Narkhede', leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c2', name: 'build', status: 'ACTIVE', issueCount: 197, lead: 'Jun Rao', leadAvatar: null, description: 'gradle', defaultAssignee: 'Project default' },
  { id: 'c3', name: 'clients', status: 'ACTIVE', issueCount: 1631, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c4', name: 'compression', status: 'ACTIVE', issueCount: 23, lead: 'Neha Narkhede', leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c5', name: 'config', status: 'ACTIVE', issueCount: 187, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c6', name: 'connect', status: 'ACTIVE', issueCount: 1154, lead: 'Ewen Cheslack-Postava', leadAvatar: null, description: 'Connect packages and connectors', defaultAssignee: 'Project default' },
  { id: 'c7', name: 'consumer', status: 'ACTIVE', issueCount: 1214, lead: 'Neha Narkhede', leadAvatar: null, description: 'consumer', defaultAssignee: 'Project default' },
  { id: 'c8', name: 'contrib', status: 'ACTIVE', issueCount: 13, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c9', name: 'controller', status: 'ACTIVE', issueCount: 271, lead: 'Neha Narkhede', leadAvatar: null, description: 'distributed co-ordination controller', defaultAssignee: 'Project default' },
  { id: 'c10', name: 'core', status: 'ACTIVE', issueCount: 1867, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c11', name: 'docker', status: 'ACTIVE', issueCount: 13, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c12', name: 'docs', status: 'ACTIVE', issueCount: 95, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c13', name: 'documentation', status: 'ACTIVE', issueCount: 273, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c14', name: 'generator', status: 'ACTIVE', issueCount: 4, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c15', name: 'group-coordinator', status: 'ACTIVE', issueCount: 77, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c16', name: 'jbod', status: 'ACTIVE', issueCount: 14, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c17', name: 'kip', status: 'ACTIVE', issueCount: 4, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c18', name: 'kraft', status: 'ACTIVE', issueCount: 281, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c19', name: 'log', status: 'ACTIVE', issueCount: 542, lead: null, leadAvatar: null, description: 'Log storage layer', defaultAssignee: 'Project default' },
  { id: 'c20', name: 'metadata', status: 'ACTIVE', issueCount: 156, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c21', name: 'mirrormaker', status: 'ACTIVE', issueCount: 188, lead: null, leadAvatar: null, description: 'MirrorMaker replication tool', defaultAssignee: 'Project default' },
  { id: 'c22', name: 'network', status: 'ACTIVE', issueCount: 387, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c23', name: 'producer', status: 'ACTIVE', issueCount: 623, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c24', name: 'replication', status: 'ACTIVE', issueCount: 731, lead: 'Jun Rao', leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c25', name: 'security', status: 'ACTIVE', issueCount: 412, lead: null, leadAvatar: null, description: 'Security features and authentication', defaultAssignee: 'Project default' },
  { id: 'c26', name: 'streams', status: 'ACTIVE', issueCount: 2043, lead: 'Matthias J. Sax', leadAvatar: null, description: 'Kafka Streams processing library', defaultAssignee: 'Project default' },
  { id: 'c27', name: 'tiered-storage', status: 'ACTIVE', issueCount: 94, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c28', name: 'tools', status: 'ACTIVE', issueCount: 318, lead: null, leadAvatar: null, description: 'Command line tools', defaultAssignee: 'Project default' },
  { id: 'c29', name: 'transaction', status: 'ACTIVE', issueCount: 204, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
  { id: 'c30', name: 'unit-tests', status: 'ARCHIVED', issueCount: 45, lead: null, leadAvatar: null, description: null, defaultAssignee: 'Project default' },
];

export const MOCK_RELEASES: JiraReleaseVersion[] = [
  { id: 'r1', name: '4.3.0', status: 'Unreleased', startDate: '2026-01-01', releaseDate: '2026-06-01', description: 'Next major release with KIP-1251 and KIP-1274 support' },
  { id: 'r2', name: '4.2.1', status: 'Unreleased', startDate: '2025-12-01', releaseDate: '2026-03-01', description: 'Patch release for critical bug fixes' },
  { id: 'r3', name: '4.2.0', status: 'Released', startDate: '2025-09-01', releaseDate: '2025-12-15', description: 'Minor release with performance improvements' },
  { id: 'r4', name: '4.1.0', status: 'Released', startDate: '2025-05-01', releaseDate: '2025-08-20', description: 'Minor release with Connect improvements' },
  { id: 'r5', name: '4.0.0', status: 'Released', startDate: '2025-01-01', releaseDate: '2025-04-10', description: 'Major release removing ZooKeeper dependency' },
  { id: 'r6', name: '3.9.0', status: 'Released', startDate: '2024-09-01', releaseDate: '2024-12-05', description: 'Last release with ZooKeeper support' },
  { id: 'r7', name: '3.8.1', status: 'Released', startDate: '2024-08-01', releaseDate: '2024-10-15', description: 'Patch release' },
  { id: 'r8', name: '3.8.0', status: 'Released', startDate: '2024-06-01', releaseDate: '2024-09-01', description: 'Minor release' },
  { id: 'r9', name: '4.4.0', status: 'Unreleased', startDate: '2026-06-01', releaseDate: '2026-11-01', description: 'Future release' },
];
